// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://injihzgvpbnzwswshigt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imluamloemd2cGJuendzd3NoaWd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMzgxMTcsImV4cCI6MjA3MDYxNDExN30.uFWwO0oGZTefQ5ndUC7rXDu89zgdz99ghYw4lbPbyXc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});